### ISSUE TITLE
libclang header files not found

### ISSUE THREAD

**Issue by cicilzx** [foonathan/cppast#100]
I am building the cppast on ubuntu, but it failed.

$ sudo cmake ../
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Installing type_safe via submodule
-- Installing debug_assert via submodule
-- Installing tiny-process-library via submodule
-- Installing cxxopts via submodule
-- cxxopts version 2.2.0
-- Found llvm-config at /usr/bin/llvm-config-6.0
-- Using LLVM version 6.0.0
CMake Error at external/external.cmake:166 (message):
  libclang header files not found
Call Stack (most recent call first):
  external/external.cmake:238 (_cppast_find_libclang)
  CMakeLists.txt:32 (include)

-- Configuring incomplete, errors occurred!
See also "/home/cici/Documents/cppast/build/CMakeFiles/CMakeOutput.log".
See also "/home/cici/Documents/cppast/build/CMakeFiles/CMakeError.log".

**Comment by MetaPostRocker** [comment]
Installing libclang by [apt](https://zoomadmin.com/HowToInstall/UbuntuPackage/libclang-dev) solved my problem
