### ISSUE TITLE
Parsed file contains 0 entities?

### ISSUE THREAD

**Issue by DethRaid** [foonathan/cppast#106]
I'm trying to use `cppast` to automatically generate code for classes with a specific C++ custom attribute. I have my codegen tool set up to parse all the header files in a specific folder. I can parse them just fine, but when I look through the parse results I only have `cpp_file` entities - no class entities, not in any file

[Here](https://github.com/DethRaid/SanityEngine/blob/trunk/SanityEngine.Codegen/src/SanityEngine.Codegen.cpp#L131) is the code I use to iterate over the entities in a file. When I put a breakpoint here and inspect each `file`, there's no entities in the file. [A screenshot of the VS variable inspector.](https://imgur.com/a/lChcGdY) As you can see, the `file`'s entity container is empty. [This](https://github.com/DethRaid/SanityEngine/blob/trunk/SanityEngine/src/adapters/rex/rex_wrapper.hpp) is the source file I'm looking at the parse result of. As you can see, this file has a number of entities

Is there anything obviously wrong that I'm doing which would cause `cppast` to think that my file contains no entities?

**Comment by foonathan** [comment]
I think there was an issue with pragma once, what happens when you run the tool on the header file?

**Comment by DethRaid** [comment]
I ran the tool with the command 
```
.\cppast.exe --database_dir src --std c++20 -I"E:\Documents\SanityEngine\SanityEngine\extern\rex\include" -I"E:\Documents\SanityEngine\SanityEngine\extern\physx\include" -I"E:\Documents\SanityEngine\SanityEngine\extern\physx\include\physx" -I"E:\Documents\SanityEngine\SanityEngine\extern\rex\include" -I"E:\Documents\SanityEngine\SanityEngine\extern\tracy" -I"E:\Documents\SanityEngine\SanityEngine\extern\json5\include" -I"E:\Documents\SanityEngine\SanityEngine\extern\dotnet\include" -I"E:\Documents\SanityEngine\SanityEngine\extern\D3D12MemoryAllocator" -I"E:\Documents\SanityEngine\SanityEngine\extern\bve\include" -I"E:\Documents\SanityEngine\SanityEngine\extern\pix\include" -I"E:\Documents\SanityEngine\SanityEngine\extern" -I"E:\Documents\SanityEngine\SanityEngine\src" -I"E:\Documents\SanityEngine\vcpkg_installed\x64-windows\include" -I"E:\Documents\SanityEngine\SanityEngine\src"  -DWIN32 -D_WINDOWS -DTRACY_ENABLE -DRX_DEBUG -DGLM_ENABLE_EXPERIMENTAL -D_CRT_SECURE_NO_WARNINGS -DGLM_FORCE_LEFT_HANDED -DNOMINMAX -DWIN32_LEAN_AND_MEAN -DGLFW_DLL -DCMAKE_INTDIR=Debug
```
with `E:\Documents\SanityEngine\SanityEngine` as the working directory

I got no output in my terminal

**Comment by foonathan** [comment]
Ok, I'm guessing if you remove the `#pragma once` it works.

I'll see what I can do.

**Comment by DethRaid** [comment]
I tried converting the `#pragma once` in my header file with a `#ifndef` include guard, but still had the same problem

I looked through the files included by that file to see if any used `#pragma once`. A few do. I can edit my local copies of my dependencies - except that MSVC's C++ standard library also uses `#pragma once`. I do not feel comfortable editing my local copy of the C++ standard library

**Comment by foonathan** [comment]
Okay, running `./cppast SanityEngine/src/adapters/rex/rex_wrapper.hpp -I SanityEngine/extern/rex/include/` in a clone of your repo works for me as intended. Could you post your compile_commands.json?

**Comment by DethRaid** [comment]
[compile_commands.json](https://github.com/foonathan/cppast/files/5331663/compile_commands.json.txt) (had to rename the file cause GitHub doesn't like .json)

[Here](https://github.com/DethRaid/SanityEngine/blob/trunk/SanityEngine.Codegen/src/SanityEngine.Codegen.cpp#L27) is the code I'm using to generate the compilation commands file

**Comment by foonathan** [comment]
OK, so `c++20` for `--std` is not valid, the best you can do is `c++1z` at the moment. I'm getting an error as expected when trying to run it. You're not getting anything?

**Comment by gmueckl** [comment]
I think I encountered a similar issue. For some reason, the cppast tool does not seem to like backslashes in a path to an input file and the resulting AST is empty. If the backslashes in the path are replaced by slashes, the output is generated as expected.

**Comment by firodj** [comment]
I face similar issue, as @gmueckl suggest, and try to fix this: https://github.com/firodj/cppast/commit/35d5155216fa970b76dfda01ef52632e05457bcd

**Comment by foonathan** [comment]
Ahh, that makes a lot of sense!

Thank you for the fix. I don't have a dev setup on Windows, so if you confirm that it works, please make a PR!

**Comment by tustin2121** [comment]
Request to reopen this bug: I'm **still** getting this problem even with the latest release. My compile_commands.json is generated on a window machine, and so literally every path in there uses `\\` as a directory separator. I did a find-replace-all of `\\` to `/` in compile_commands.json, and _suddenly_ the diagnostic logger is printing all sorts of info about the file to my logs! I can't do that find-replace as part of my build process -- cmake just generates that file out of the blue -- so this is kind of impossible to work around at the moment... 

Without replacing every backslash with a slash in that file, literally nothing seems to happen (and the debug *.pp files are all blank) otherwise. Nothing seems to happen, but it sure is taking a lot of time to do the nothing... so it's clearly doing a whole lot of something then discarding it all or something.

**Comment by foonathan** [comment]
Great, can you do a PR?
