### ISSUE TITLE
Idea: consider a header-only version of tiny-process-library

### ISSUE THREAD

**Issue by eyalroz** [foonathan/cppast#113]
So, I've started taking an interest in cppast and its dependencies...

One early thing I want to suggest to you is to reduce dependencies on libraries which need compilation. So, I've adapted tiny-process-library to be header-only:

https://gitlab.com/eyalroz/tiny-process-library/-/tree/better_header_only

the library author does [not seem to be thrilled](https://gitlab.com/eidheim/tiny-process-library/-/issues/50) about this possibility.

**Comment by foonathan** [comment]
If I recall correctly, tiny process is just one header plus source or so, so I would be fine simply vendoring it, i.e. add them to this git repo directly.

**Comment by foonathan** [comment]
I did that myself.
