### ISSUE TITLE
FetchContent downloads type_safe on every CMake generation

### ISSUE THREAD

**Issue by osdeverr** [foonathan/cppast#117]
* cppast version: Latest
* OS: macOS
* Generator: Xcode

Apparently it fails to find the type_safe package every time and thus redownloads it. I suggest you just reintroduce type_safe as a Git submodule, remove find_package and include type_safe in your CMakeLists.txt as a subdirectory: there really isn't a need for FetchContent in this case. (Correct me if I'm wrong)
By the way, this library is extremely useful. Thanks for creating it!

**Comment by foonathan** [comment]
It prints `Fetching type_safe` every time, but doesn't actually re-download it again unless you delete it from the build folder.

**Comment by osdeverr** [comment]
> It prints `Fetching type_safe` every time, but doesn't actually re-download it again unless you delete it from the build folder.

Are you sure? I'm not that familiar with CMake but there is indeed a noticeable delay in the generation once the `Fetching type_safe` message shows up. Plus, it seems that it's not displayed _every_ time; rather, it's only shown if the package is missing.
![image](https://user-images.githubusercontent.com/10074604/111324755-1ae1bb80-867c-11eb-8f54-8b282a58b709.png)

**Comment by foonathan** [comment]
The documentation says so: https://cmake.org/cmake/help/latest/module/FetchContent.html

**Comment by osdeverr** [comment]
Got it, thanks.
