### ISSUE TITLE
Any chance for examples of common usage?

### ISSUE THREAD

**Issue by sztomi** [foonathan/cppast#13]
Right now it's hard to see where to get started, what are the main "entry points" from the library users' perspective. Examples of extracting member functions, attributes, enums etc. would be great.

**Comment by foonathan** [comment]
[The tool](tool/main.cpp) shows how to print the AST, it should be easy to understand.

But I need proper examples, yes.

**Comment by foonathan** [comment]
What kind of examples would you find useful?

**Comment by sztomi** [comment]
* Extracting member functions of a class
  * Extracting enums and their members (maybe even a complete example of enum->string, string->enum function generation)
  * Reading [[attributes]] of the current node
  * Getting the original source line(s) where the current node is written
  * Source-to-source transformations, when rewriting becomes available

**Comment by foonathan** [comment]
> Reading [[attributes]] of the current node

Attributes are currently not supported, but will be the first thing I'll take care of as soon as cppast is integrated into standardese.

> Getting the original source line(s) where the current node is written

I'm afraid that is not possible as my preprocessor changes the amount of newlines. Do you have a scenario in mind where that is necessary?

**Comment by sztomi** [comment]
> Attributes are currently not supported, but will be the first thing I'll take care of as soon as cppast is integrated into standardese.

Awesome, I think this is very important for tools that use the library.

> Do you have a scenario in mind where that is necessary?
Well, mainly it was my escape when libclang was not giving to full AST, so if I needed to find out something that libclang did not tell me, I could do some crude parsing. I understand that you do this yourself, so this use-case might not be so valid for cppast. On the other hand it could be useful for an IDE, or source code explorer application, where it can show the declaration in some form. Or even for standardese.

**Comment by foonathan** [comment]
I hope that you don't need to do crude parsing when using cppast ;)

Regarding IDE application, I see how that can be useful; even the current cppast error messages can't don't show line numbers, just file + entity name, so there could be some improvement.

**Comment by foonathan** [comment]
I've added a couple of examples in the example/ directory, what do you think?

**Comment by sztomi** [comment]
They seem very helpful. One possible improvement would be providing example inputs and outputs for the programs in comments, e.g. here is a source as input, the program will generate this and that as output. Otherwise, I'm happy with them, thanks for taking the time.

**Comment by foonathan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Test](https://trello.com/c/B478Ouds/1-test)

**Comment by sztomi** [comment]
There is also waffle.io which seems to integrate better than trello (I use it in rpclib)

**Comment by foonathan** [comment]
:D

Sorry, about that, didn't realize it would do that.

Yes, I'm aware but I want to manage other things besides GitHub issues.
