### ISSUE TITLE
Is possible to get the #if defined directives information through cppast? 

### ISSUE THREAD

**Issue by littleGnAl** [foonathan/cppast#131]
Thanks for this awesome library!

I'm trying to generate a gmock file by using cppast, I have a class like below:
```c++
class Engine {
 public:
   virtual int setAppType1(int app_type) = 0;

  #if (defined(TARGET_OS_IOS))
   virtual int setAppType2(int app_type) = 0;
  #endif
};
```

The generated file content should like:
```c++
class MockEngine {
 public:
  MOCK_METHOD(int, setAppType1, (int app_type), (override));

  #if (defined(TARGET_OS_IOS))
  MOCK_METHOD(int, setAppType2, (int app_type), (override));
  #endif
}
```
Is possible to get the `  #if (defined(TARGET_OS_IOS))` directives information through cppast? Any suggestion for this?

**Comment by foonathan** [comment]
No, that is not possible, and I don't think it ever will be possible, unfortunately. libclang works on the input after it has been preprocessed. Getting macro definitions is already a hack on their end, and I need to do extra work to hide declarations from header files, etc.
