### ISSUE TITLE
How to get the initialization block of the constructor?

### ISSUE THREAD

**Issue by littleGnAl** [foonathan/cppast#136]
I want to get the initialization block of the constructor, so I can get the default value of the member variable, e.g.
```c++
struct AudioTrackConfig {
  bool enableLocalPlayback;
  AudioTrackConfig() : enableLocalPlayback(true) {}
};
```
It seems there's not enough information to do this by parsing the `cpp_constructor`, can you give me some guide to do this?

**Comment by foonathan** [comment]
That is part of the definition, and cppast doesn't expose the definitions of entities. You have to use libclang or libtooling directly.

**Comment by littleGnAl** [comment]
Is possible for cppast to support it?

**Comment by foonathan** [comment]
Not without a lot of work, which I don't have the time or energy for.
