### ISSUE TITLE
Better to_string for cpp_dependent_type

### ISSUE THREAD

**Issue by deadlocklogic** [foonathan/cppast#148]
Dependent types should be named as: `typename dependee::name` but in the current implementation only the name appears when calling `cppast::to_string`.
```C++
void write_dependent(code_generator::output& output, const cpp_dependent_type& type)
{
    output << token_seq(type.name());
}
```
Maybe use the dependee type in this snippet for better naming?
Thnaks.

**Comment by foonathan** [comment]
The libclang parser never generates a `cpp_dependent_type` actually, so I'm curious why you ran into that issue? Nevertheless, it is now formatted properly.

**Comment by deadlocklogic** [comment]
I made a `TypeUtils` class which (parses/clones/prints/sanitizes/resolves) `cpp_type`. So yeah I am stretching the boundaries a bit with this library.
