### ISSUE TITLE
Clang 15 - minor breaking change and opportunity for enhancements

### ISSUE THREAD

**Issue by waitingtocompile** [foonathan/cppast#155]
* cppast version: 4143cea00f9ac2c8f2dc71f20cc52cc3370286c9
* parser: `libclang_parser`
* clang version: 15.0.5

Clang 15 introduces several new cursor types, exposing a lot of new functionality. However, it also means that concept definitions have been given their own cursor, which is currently unhandled. I'm more than happy to make the fix accounting for the new cursor type, as well as see if there's any enhancements to be applied from the increasced support from libclang, however before I do I'd like guidance on how you would want me to handle backwards compatability.

**Comment by foonathan** [comment]
I welcome a PR, since I don't have clang 15 at the moment to test it out.

> however before I do I'd like guidance on how you would want me to handle backwards compatability.

You can use conditional compilation based on `CINDEX_VERSION_MINOR`.
