### ISSUE TITLE
Problem with getting function templated type arguments

### ISSUE THREAD

**Issue by mVento3** [foonathan/cppast#158]
I have some weird problem with getting function arguments type. For some reason instead of getting templated type I am getting int. I have found a workaround using typedefs but it is a bit annoying.

Here an example:
```cpp
void GenerateCustom(std::ofstream& _hFile, std::ofstream& _sFile, std::vector<std::pair<uint32_t, std::vector<std::string>>>& _aGenerated);
```
Instead of getting `std::vector<...>&` I am getting int reference (the same is with std::filesystem::path).

Here is the code to get the arguments type:
```cpp
//const cppast::cpp_member_function& _entity;
//compile_config _config;

//_config.fast_preprocessing(true);
//_config.set_flags(cppast::cpp_standard::cpp_latest);

for(const auto& _arg : _entity.parameters())
{
    __ast_entity_argument _eArg;

    _eArg.m_sName = _arg.name();
    _eArg.m_sType = to_string(_arg.type());

    _pScope->m_aArguments.push_back(_eArg);
}
```
![image](https://user-images.githubusercontent.com/7684287/213921013-521c00d4-cced-4255-aebb-07c132899f9d.png)

Is that even supported? All I need is a string of this type.

* cppast version: latest
* parser: libclang_parser
* clang version: 15.0.6

**Comment by mVento3** [comment]
The problems was I did not define some of my needed definitions in config which resulted in parsing error, and the default type in libclang is int, issue solved.

**Comment by benkoska** [comment]
I ran into the same problem. Would you mind sharing exactly which config change(s)/definitions fixed the problem?
