### ISSUE TITLE
Filtered node visitation

### ISSUE THREAD

**Issue by sztomi** [foonathan/cppast#17]
I started playing with the library and I found myself often writing visitor callbacks, that:

  * Filter out "exit" tokens
  * Blacklist-style filter out certain entity types (e.g. file node)
  * Whitelist-style filter for certain node types ("iterate over only enums")

Some form of declarative filtering would be quite useful, e.g. 

```cpp
visit(file, cppast::whitelist(cpp_entity_type::enum_t, cpp_entity_type::class_t), [&](const cpp_entity& e, visitor_info info) {
```

or

```cpp
visit(file, cppast::blacklist(cpp_entity_type::enum_value_t, cpp_entity_type::struct_t), [&](const cpp_entity& e, visitor_info info) {
```

(not sure about the syntax, but you get the idea). As for the enter-exit events, it might even make sense to provide a simple_visit function that only does `enter` events, since that's a large use-case.

**Comment by foonathan** [comment]
`visit()` is a relatively primitive visitation mechanism, yes.

The original clang API provides something called AST matchers that provide high level access, an implementation for cppast is planned.

**Comment by sztomi** [comment]
Matchers would be very cool, though I think there would be value in whitelist-backlist visitor and it would be fairly easy to implement. Would you be interested in a PR if I implemented it?

**Comment by foonathan** [comment]
I can see your point, I'd be happy if you do a PR.

I'd suggest you add a second `visit()` overload taking a predicate which controls whether or not the visitor will be called and then create, e.g. a `whitelist()` function to easily create that predicate. This should be fairly extensible.

**Comment by sztomi** [comment]
I have a [WIP implementation now](https://github.com/sztomi/cppast/commit/fdbd571841278a0095858dc30a0aeeb56f6a5ff7) (don't worry about the unneeded includes and other cruft, it's going to be cleaned up). I have a question: where should I put the unit tests? In a separate file? Also, are you OK with putting `whitelist` and `blacklist` into cpp_entity.hpp? The reason for not putting it into cpp_visitor.hpp is that they need to call `kind` but `cpp_entity` is only forward declared there.

**Comment by foonathan** [comment]
WIP seems good, I'll add comments.

>  where should I put the unit tests? In a separate file?

Yes, I'd suggest that.

> The reason for not putting it into cpp_visitor.hpp is that they need to call kind but cpp_entity is only forward declared there.

I'd rather put them in `visitor.hpp` and include `cpp_entity.hpp` there (should work afaik), I did a lot of work to ensure `cpp_entity.hpp` does not include entity kind.

**Comment by sztomi** [comment]
OK, if including is not a problem then I'll go with that.
