### ISSUE TITLE
CppParser.ParseFile() call hangs

### ISSUE THREAD

**Issue by sabuncu** [foonathan/cppast#172]
* cppast version: Latest
* parser: `libclang_parser` 
* clang version: 15.0.1

I created a console application, which works 50% of the time.  Every other time (i.e. after starting the application from scratch on the command line), the `CppParser.ParseFile()` call hangs.  Same with the `CppParser.Parse()` call.

What could be the problem, or how can I go about debugging this problem?

Thanks.

Input:

I am using the code in the documentation.

```cpp
Minimal source code reproducing the error
```

Input flags: 

Output:

```
Output of `cppast -v <input>`
```

**Comment by foonathan** [comment]
I think you meant to share this to https://github.com/xoofx/CppAst.NET

**Comment by sabuncumurat** [comment]
Sorry about that.
