### ISSUE TITLE
Compilation database parsing

### ISSUE THREAD

**Issue by sztomi** [foonathan/cppast#19]
I'm reading a compilation database, and I don't want to use the flags abstractions to supply the flags to the config. I would have to parse the string flags just have cppast put the same string together. So, is there a way to set the directly?

**Comment by foonathan** [comment]
I want to support compilation databases anyway, so I think a better option would be to implement that. How are you parsing the database?

**Comment by sztomi** [comment]
Something like this:

```cpp
using compdb_t = std::unordered_map<std::string, std::string>;

compdb_t get_header_compdb(std::string const& file_name) {
  compdb_t result;
  std::fstream compdb_file(file_name, std::ios::in);

  auto extract_flags = [](std::string p) {
    constexpr auto cmd = "c++   ";
    const size_t cmd_pos = p.find_first_of(cmd);
    if (std::string::npos != cmd_pos) {
      p.erase(0, cmd_pos - 2 + sizeof(cmd)/sizeof(char));
    }
    const auto minus_o_pos = p.rfind("-o");
    if (std::string::npos != minus_o_pos) {
      p.erase(minus_o_pos);
    }
    return p;
  };

  auto compdb = json::parse(compdb_file);
  for (auto &v : compdb) {
    auto f = filename_without_ext(v["file"]);
    auto flags = extract_flags(v["command"]);
    result[f] = flags;
  }
  return result;
}
```

The reason for removing the extensions is that the compdb will only contain sources, but I want to parse headers. This is an imperfect workaround for that (based on the assumption that a similarly named source includes a similarly named header). It's hard, really, because defines on the command line mean you might get a different AST when you use different flags. 

I have another, weaker assumption that may not hold for all projects: that the file names are unique all around the directory tree. It would be better to calculate the relative path of the files from a common root, but I didn't need to do that.

Then, I just iterate the files I want to parse with cppast, and set the flags for each one like this:

```cpp
void set_flags(cppast::libclang_compile_config &cfg,
               std::string const &flags_str) {
  auto flags = split(flags_str, ' ');

  auto is_empty = [](std::string const& s) {
    return s.find_first_not_of(' ') == std::string::npos;
  };
  auto starts_with = [](std::string const &s, std::string const &pref) {
    return s.find(pref) == 0;
  };

  for (auto &f : flags) {
    if (is_empty(f)) {
      continue;
    }
    if (starts_with(f, "-D")) {
      auto parts = split(f.substr(2), '=');
      if (parts.size() == 2) {
        cfg.define_macro(parts[0], parts[1]);
      }
      else {
        cfg.define_macro(parts[0], "");
      }
    }
    else if (starts_with(f, "-I")) {
      cfg.add_include_dir(f.substr(2));
    }
  }
}
```

Again, a number of assumptions that are fit for my case, but in a generic setup should be handled better. I'm using this json library: https://github.com/nlohmann/json

**Comment by foonathan** [comment]
I'll probably use the libclang API like I did in standardese: https://github.com/foonathan/standardese/blob/master/src/config.cpp#L62

> The reason for removing the extensions is that the compdb will only contain sources, but I want to parse headers. This is an imperfect workaround for that (based on the assumption that a similarly named source includes a similarly named header). It's hard, really, because defines on the command line mean you might get a different AST when you use different flags.

Yeah, that is a problem. My previous workaround was simply appending the options of all files. A real solution would probably to do automatic include parsing when reading a translation unit or something like that.

Anyways, I'm off to C++Now, I could work on that in two weeks or so.

**Comment by sztomi** [comment]
> A real solution would probably to do automatic include parsing when reading a translation unit or something like that.

Yes, that's the closest to being correct. Unfortunately it's still possible that a header is included in multiple sources with a different set of defines, leading to different ASTs.

**Comment by foonathan** [comment]
So I've implemented compilation database parsing.

I didn't solve the problem of header parsing: The user has to specify which file should be used from the database. I've also added a facility for parsing multiple files at once.

**Comment by sztomi** [comment]
Good news :) Thanks for the update. As for the header parsing, maybe it would make sense to optionally let the user say that the flags of the corresponding source should be used automatically (as if they were defined with the same flags in the compdb). I think this would cover the majority of use-cases.

**Comment by foonathan** [comment]
There is a `resolve_headers()` function that takes a file and a configuration and parses all headers of the file using that configuration.
There is also `parse_files()` that takes a list of files and a compilation database and uses the information in the database to parse the files, ignoring extensions when looking for a match.

This should cover all use cases as well.

**Comment by sztomi** [comment]
Sounds great, thanks!
