### ISSUE TITLE
Comments in macro parameter lists trigger an error

### ISSUE THREAD

**Issue by torokati44** [foonathan/cppast#22]
* cppast version: 0.0 (1053429b)
* parser: `libclang_parser`
* clang version: 3.9.1

Input:

```cpp
#define ADD(A /* plus */, B) ((A) + (B))
```

Input flags: 

none

Output:

[preprocessor] [error] main.cpp:3: expected comma in macro parameter list
[fatal parsing error] preprocessor: command '/usr/bin/clang -x c++ -I. -E -CC -dD -fno-caret-diagnostics -fno-show-column -fdiagnostics-format=msvc -Wno-pragma-once-outside-header -Wno-pragma-system-header-outside-header -Wno-include-next-outside-header -I/usr/lib64/clang/3.9.1/include -D__cppast__=libclang -D__cppast_version_major__=0 -D__cppast_version_minor__=0 -std=c++14 "main.cpp"' exited with non-zero exit code (1)

Output of `cppast -v <input>`

(the exact same error as above)

**Comment by torokati44** [comment]
Just came to my mind (right after submitting, of course) that I should have tried it with clang 4.0.0. But it takes so long to build LLVM...
Do you think that would have helped?

**Comment by foonathan** [comment]
There are precompiled binaries available for common systems, cppast can even download them automatically if you pass some CMake option (don't remember the name right now ːD).

But no, this would not have helped, this is an error on my part.

**Comment by foonathan** [comment]
Okay, this isn't an error on my part but a clang bug in the `-CC` option, I'll report it later.

There are a two solutions:

1. Don't pass `-CC` when preprocessing, just `-C`. This has the downside that you won't get documentation comments if they're generated by macro, which I'd want for standardese later on.

2. Don't allow comments in macro parameters which would mean changes in your code.

Making the choice customizable would probably be a good idea.

**Comment by torokati44** [comment]
Thanks for the rapid response!

I went ahead with option 2 already, and it only needed a single change, but I don't think it's feasible in the long run. Even option 1 wouldn't be that bad for me. But let's hope the -CC option will be fixed in clang soon, so we won't need either!

**Comment by foonathan** [comment]
Bug report is here: https://bugs.llvm.org/show_bug.cgi?id=33609

**Comment by foonathan** [comment]
I had to pick option 1 here due to other issues, so I'm closing this one.
