### ISSUE TITLE
LIBCLANG_LIBRARY-NOTFOUND.lib

### ISSUE THREAD

**Issue by dry11orange** [foonathan/cppast#25]
* cppast version: <latest one>
* parser: `libclang_parser` 
* clang version: <4.0.1>

compile error:
1>------ 已启动生成: 项目: cppast_test, 配置: Debug Win32 ------
2>------ 已启动生成: 项目: cppast_tool, 配置: Debug Win32 ------
2>LINK : fatal error LNK1104: 无法打开文件“LIBCLANG_LIBRARY-NOTFOUND.lib”
1>LINK : fatal error LNK1104: 无法打开文件“LIBCLANG_LIBRARY-NOTFOUND.lib”

I can't find the library in clang or llvm project.
I don't understand why the library name.

**Comment by foonathan** [comment]
cppast requires libclang which you do not have installed.

You need to install it and - for Windows - set the CMake variables to the correct values as described in the README here:

> For that set the option LLVM_VERSION_EXPLICIT to the version you're using, LIBCLANG_LIBRARY to the location of the libclang library file, LIBCLANG_INCLUDE_DIR to the directory where the header files are located (so they can be included with clang-c/Index.h), LIBCLANG_SYSTEM_INCLUDE_DIR where the system header files are located (i.e. stddef.h etc, usually under prefix/lib/clang/<version>/include) and CLANG_BINARY to the full path of the clang++ exectuable.

For example, under Appveyor I use the following CMake invocation:
>  `cmake -G"Visual Studio 14 2015 Win64" -DLLVM_VERSION_EXPLICIT=4.0.0 -DLIBCLANG_LIBRARY="C:/Program Files/LLVM/lib/libclang.lib" -DLIBCLANG_INCLUDE_DIR="C:/Program Files/LLVM/include" -DLIBCLANG_SYSTEM_INCLUDE_DIR="C:/"Program Files"/LLVM/lib/clang/4.0.0/include" -DCLANG_BINARY="C:/Program Files/LLVM/bin/clang++.exe" ../
`
