### ISSUE TITLE
Attribute list incorrect with declarators

### ISSUE THREAD

**Issue by martty** [foonathan/cppast#27]
Thanks for implementing attributes! I was initially the guy requesting them on your blog, so I am super happy! (the readme still says no attributes, so that is why it took me sometime to start testing)

* cppast version: `latest`
* parser: `libclang_parser` 
* clang version: `5.0`

Input:
```cpp
struct [[reflect]] my_struct{
  [[property1]] int foo;
} [[property2]] bar;
```

Input flags: `-std=c++1z`

For this struct, `my_struct` will have 1 attribute (correct), `foo` will have 1 attribute (correct) and `bar` will have 3 attributes [reflect, property1, property2], which I think is incorrect, it should only have 1 attribute (property2). Of course this is easily worked around by moving the declarator.

A possibly separate issue is that attributes after declarators are ignored.

**Comment by foonathan** [comment]
Right, I need to work on the parsing code for such variable declarations...
