### ISSUE TITLE
std::atoi throws invalid argument exception

### ISSUE THREAD

**Issue by Manu343726** [foonathan/cppast#33]
* cppast version: master ca2fae08a2c50c9759433b5abb1345fc78dcfc55
* parser: `libclang_parser`
* clang version: 5.0

While parsing a header file with my libclang parser instance, an `std::atoi()` call throws an `std::invalid_argument` exception. Seems to be a regression introduced by #32 (My previous working version of cppast was master 24365e8b8288c8949e9585d0dda4b59c69d0b6b2, the issue started after updating my project submodules).

I've set up a branch of my project with the mentioned ca2fae08a2c50c9759433b5abb1345fc78dcfc55 cppast commit to reproduce the error, named `type_safe_atoi_throws`. [Here](https://gitlab.com/Manu343726/tinyrefl/pipelines/16562483)'s a link to the latest CI build of that branch.  (The project has not been released yet, but I've added your gitlab account as a guest).

For reference, [here](https://gitlab.com/Manu343726/tinyrefl/pipelines/16560833)'s the same build in the master branch, which uses the cppast commit 24365e8b8288c8949e9585d0dda4b59c69d0b6b2.

Both builds are run in a docker container with an image named [`geordiejones/cpp14-build-machine`](https://hub.docker.com/r/geordiejones/cpp14-build-machine/), which provides a minimal libclang-5 ubuntu environment. The issue happens when running my [`tool`](https://gitlab.com/Manu343726/tinyrefl/blob/cppast_atoi_throws/tool.cpp) with [my example header](https://gitlab.com/Manu343726/tinyrefl/blob/cppast_atoi_throws/example.hpp).

Also for reference, here's the commit in the `type_safe_atoi_throws` branch, the difference from master:

```
commit 38885f6b8b98ef94176f5127d66a91e3dd659912
Author: Manuel Sanchez <manuel@by.com.es>
Date:   Wed Jan 24 09:19:40 2018 +0000

    update cppast version to ca2fae08a2c50c9759433b5abb1345fc78dcfc55

diff --git a/cppast b/cppast
index 24365e8..ca2fae0 160000
--- a/cppast
+++ b/cppast
@@ -1 +1 @@
-Subproject commit 24365e8b8288c8949e9585d0dda4b59c69d0b6b2
+Subproject commit ca2fae08a2c50c9759433b5abb1345fc78dcfc55
```

**Comment by foonathan** [comment]
https://gitlab.com/Manu343726/tinyrefl/blob/cppast_atoi_throws/example.hpp

This link isn't working for me.

**Comment by foonathan** [comment]
Anyway, I've improved the fix of #32 in bca488c3d7acdf7156881c9a763cd43dc035183f, maybe that fixes your issue?

**Comment by foonathan** [comment]
There is, and I can access this https://gitlab.com/Manu343726/tinyrefl/.

**Comment by Manu343726** [comment]
So you have access to the root of the repo but not to a file in another branch? That's weird xd

Anyway, the example.hpp file is the same in both branches (or almost the same, maybe a method or a variable is missing from the C class)

**Comment by foonathan** [comment]
I don't see any files there though. It's just empty.

**Comment by Manu343726** [comment]
Maybe it has something to do with your account set as "guest" (vs dev or something).

**Comment by Manu343726** [comment]
So it seems that guests are not allowed to download the project....

Try again (sorry)

**Comment by foonathan** [comment]
Now it works and the fix I did seems to work as well.

**Comment by Manu343726** [comment]
Perfect, thanks for your patience.

**Comment by Manu343726** [comment]
Fixed https://gitlab.com/Manu343726/tinyrefl/pipelines/16657274 Thanks!

**Comment by Manu343726** [comment]
For reference, I've repro this again by adding "-v" to my parser `config.add_flag()`.

**Comment by foonathan** [comment]
I can't reproduce the error with the original example: https://gitlab.com/Manu343726/tinyrefl/blob/cppast_atoi_throws/example.hpp

**Comment by Manu343726** [comment]
Alright, I will try to create a branch tomorrow morning to repro the error in a CI build for you.

**Comment by foonathan** [comment]
Yeah, I don't know about that error — why do you want verbose output? The exception is in my diagnostic parser because it assumes that libclang issues diagnostics only and it can't really parse the version information and stuff.
