### ISSUE TITLE
cmake build only the static lib

### ISSUE THREAD

**Issue by etiam** [foonathan/cppast#36]
I'm trying to incorporate cppast into another project and so want only to build the static lib, no example, test, etc.  when i pass `-DCPPAST_BUILD_EXAMPLE=OFF -DCPPAST_BUILD_TEST=OFF -DCPPAST_BUILD_TOOL=OFF ` to the cmake command it still builds example, test, etc.  

I'm not a cmake expert but i *think* i tracked it down to this statement in CMakeLists.txt:

`if(${CPPAST_BUILD_EXAMPLE} OR (CMAKE_CURRENT_SOURCE_DIR STREQUAL CMAKE_SOURCE_DIR))`

(on line 29).  

from the cmake docs:

**CMAKE_CURRENT_SOURCE_DIR** 
this is the directory where the currently processed CMakeLists.txt is located in

**CMAKE_SOURCE_DIR** 
this is the directory which contains the top-level CMakeLists.txt, i.e. the top level source directory

so this will always be true the way i configure:

```
cd cppast
mkdir build
cmake ..

```

perhaps i'm configuring incorrectly but i thought this was the accepted cmake way.

thanks

**Comment by foonathan** [comment]
No, you're doing everything correctly.

The logic was supposed to be "never build examples/test when added with add_subdirectory(),but override that with the options". I'll fix it later today.

**Comment by etiam** [comment]
thank you.

**Comment by foonathan** [comment]
Okay, should be fixed now.
