### ISSUE TITLE
Does cppast support pch file?

### ISSUE THREAD

**Issue by chena1982** [foonathan/cppast#37]
I use vs2017, how to set the pch file path?
Thanks.

**Comment by foonathan** [comment]
No, it does not support pch, as libclang doesn't support them. (As far as I know)

**Comment by chena1982** [comment]
vs 2017, i random select a source file from a dll project, add --msvc_extensions --msvc_compatibility, add all include directory use -I, add all macro defines use -D, but result is null, no error when run the cppast tool.

Does i need set somethig else?
Thanks.

**Comment by foonathan** [comment]
No, this should work.

**Comment by foonathan** [comment]
Could you provide a minimal example that reproduces the error?

**Comment by chena1982** [comment]
Thanks for your reply.
I extract a minimal project from the original dll project.
Run test.bat for test, i just change the include directory to relative path.
[Test.zip](https://github.com/foonathan/cppast/files/1723057/Test.zip)

**Comment by foonathan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #37: Does cppast support pch file?](https://trello.com/c/P7vbxkiD/3-issue-37-does-cppast-support-pch-file)

**Comment by foonathan** [comment]
Sorry for the late reply, I was really busy.

I played around with your issue, it seems that cppast didn't find the input files properly (something with whitespaces and/or backslashes in the path), but this wasn't reported. The master branch will now issue a diagnostic when it can't find the file.

**Comment by chena1982** [comment]
Thanks for your reply.
I found the problem, -I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\" don't work, must be -I "\"C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\"".
Thanks.

I found other two problem:   
1. can you add some options to output the preprocessed file?
if i have the preprocessed file, it can help understand the error.
for example:
  >[libclang] [error] EFFArray.cpp:1905: constexpr variable '_Memcpy_move_offset' must be initialized by a    constant expression

  I don't know '_Memcpy_move_offset' in line 1905 is what, search in the whole solution, don't find anything.


2. if the "#include xxx.h" contain /**/,  will lead the clang to exit.

> [preprocessor] [error] In file included from D: \Program Files\boost_1_65_0_beta1_rc2\boost/mpl/or.hpp:43:
[preprocessor] [error] D: \Program Files\boost_1_65_0_beta1_rc2\boost/mpl/aux_/include_preprocessed.hpp(37):  fatal error: 'boost/mpl/aux_/preprocessed/plain/or.hpp /**/' file not found
[preprocessor] [error] D: \Program Files\boost_1_65_0_beta1_rc2\boost/preprocessor/stringize.hpp(28):  note: expanded from macro 'BOOST_PP_STRINGIZE'
[preprocessor] [error] D: \Program Files\boost_1_65_0_beta1_rc2\boost/preprocessor/stringize.hpp(31):  note: expanded from macro 'BOOST_PP_STRINGIZE_I'
[preprocessor] [error] <scratch space>:83: note: expanded from here

include_preprocessed.hpp:
![boost](https://user-images.githubusercontent.com/5953033/37536106-a24aa6de-2984-11e8-81f3-65ff96bdf7c1.png)




so "#include xxx.h" shouldn't contain "/**/", or is this a bug?

**Comment by foonathan** [comment]
> can you add some options to output the preprocessed file?

If you pass `-v` to the tool or set `write_preprocessed` to the config, it should generate a `.pp` file containing the preprocessed output.

Line numbers should normally match though, was any other error generated?

> if the "#include xxx.h" contain /**/, will lead the clang to exit.

I've added a new option you need to enable for this, `remove_comments_in_macro`.

**Comment by chena1982** [comment]
Thanks for your reply.
`remove_comments_in_macro` works well.

pass -v to the tool will generate the .pp file, but this file don't contain the correct info, it just have 62 lines.

i upload the new test.zip, you can play with it.
[Test.zip](https://github.com/foonathan/cppast/files/1834137/Test.zip)

thanks.

**Comment by foonathan** [comment]
The `.pp` file in the zip archive looks correct.

And the error messages are issues by libclang, it doesn't seem to support some constexpr extensions from MSVC. The only bug on my part is that the file names are wrong, I see what I can do about that.

> And i use the tool to parse the same file in my real project, it still just output empty result:

What do you mean? The above output shows a non-empty AST.

**Comment by chena1982** [comment]
>What do you mean? The above output shows a non-empty AST.

The above output is the output of the test demo.
I use the same cppast.exe to parse the same EFFArray.cpp, just change the pch file, use the real project's pch file.
The pch file is more complicated than the pch file in the test demo.

![ast](https://user-images.githubusercontent.com/5953033/38256744-9534119a-3791-11e8-941a-ae2a20307b25.png)

you can see the output, still output empty ast.
Thanks.

**Comment by foonathan** [comment]
Sorry, that it took me so long to get back to you.

I can't really reproduce the issue anymore, might have been fixed now.
