### ISSUE TITLE
How do i tell if cpp_type is enum?

### ISSUE THREAD

**Issue by rokups** [foonathan/cppast#38]
I am generating a c wrapper over api using cppast and i came to need to decide if type is complex or not. Checking cppast source code i noticed that `user_defined_t` is treated as non-complex. I may not understand what exactly is complex type here because for example user-defined class types are also `user_defined_t`. So is there a way to figure out if particular `cpp_type` is backed by a simple data type like enums are backed by integers for example?

**Comment by foonathan** [comment]
If you're referring to this https://github.com/foonathan/cppast/blob/master/include/cppast/cpp_type.hpp#L447 with complex types, they are just used for code generation and shouldn't worry you.

To detect whether or not a `cpp_type` is an `enum`, you have to see whether it is user defined, lookup the target of the user defined type and see whether that is a `cpp_enum`, example here: https://github.com/foonathan/cppast/blob/master/example/enum_category.cpp#L41-L49
