### ISSUE TITLE
Unexposed expression string representation is not complete

### ISSUE THREAD

**Issue by rokups** [foonathan/cppast#41]
* cppast version: latest
* clang version: 5.0.1

In some rare cases string representation of unexposed expression is incomplete. Happened to me exactly once, last character is missing in this case.

Input:
```cpp
void SetEventFrame(float time, const StringHash& eventType, const VariantMap& eventData = VariantMap());
```
Output:
`dynamic_cast<const cppast::cpp_unexposed_expression&>(expression).expression().as_string()` returns `VariantMap(`.

```
AST for 'Scene/ValueAnimation.h':
|-../Core/Variant.h (include directive): `#include "../Core/Variant.h"`
|-../Resource/Resource.h (include directive): `#include "../Resource/Resource.h"`
+-Urho3D (namespace)
  +-ValueAnimation (class) [definition]: `class ValueAnimation;`
    |-public (access specifier): `public:`
    |-ClassName (type alias): `using ClassName=Urho3D::ValueAnimation;`
    |-BaseClassName (type alias): `using BaseClassName=Urho3D::Resource;`
    |-SetEventFrame (member function): `void SetEventFrame(float time,Urho3D::StringHash const& eventType,Urho3D::VariantMap const& eventData=VariantMap();`

```

**Comment by foonathan** [comment]
Yeah, this is part of the same issue as #26.

**Comment by rokups** [comment]
I revisited this issue. In another bug you said

> This seems to be a clang 6 only issue, can't reproduce it with clang 5 (and don't have clang 6 available).
> Something changed in their tokenizer so now my workaround doesn't really work.

So i downgraded to 5.0.1 and issue persists.
