### ISSUE TITLE
Example using cpp_entity_index

### ISSUE THREAD

**Issue by rokups** [foonathan/cppast#42]
Hey is it possible to use `cpp_entity_index` for our own purposes? I cant really see how.

### What i am trying to do
As you know i am writing c# bindings generator. Part of the process is to drop certain parts of API that contain unknown types. Consider `Texture* GetTexture()` method. `cpp_member_function` pointing to `GetTexture()` provides return type `Texture*` as `cpp_type`. Is there any way to look into `cpp_entity_index` and see if there is class `Texture` defined? I did some debugging of cppast and i see that ids are like `"c:@N@Urho3D@S@Texture"`. I probably should not go around trying to guess them manually myself..

**Comment by foonathan** [comment]
You can get the `pointee()` type from a `cpp_pointer`, see if that's a `cpp_user_defined_type` and look a definition up using the index.

**Comment by rokups** [comment]
Indeed.. Exactly like with enums. Thank you very much :+1:

**Comment by rokups** [comment]
Oh yeah i totally forgot another usecase. For example i know a class `Foo` is declared in namespace `Bar`.  Is there any way to somehow find entity on it's full name `Foo::Bar`?

**Comment by foonathan** [comment]
Now, you'd have to build something like that yourself.
