### ISSUE TITLE
Getting arguments of template instantiation

### ISSUE THREAD

**Issue by rokups** [foonathan/cppast#43]
I am trying to get templated type parameter. This oversimplified example fails:
```cpp
if (type.kind() == cppast::cpp_type_kind::template_instantiation_t)
{
    const auto& templateType = dynamic_cast<const cppast::cpp_template_instantiation_type&>(type);
    templateType.arguments().value();    // type_safe/tagged_union.hpp:262: Assertion 'cur_type_ == type' failed - different type stored in union.
}
```
Am i doing something wrong or is this a bug?

**Comment by foonathan** [comment]
See here: https://github.com/foonathan/cppast/blob/master/include/cppast/cpp_template.hpp#L145-L168

In your case the arguments aren't exposed so you only get them as string via `unexposed_arguments()`. See also #9.
