### ISSUE TITLE
Extracting constructor signature

### ISSUE THREAD

**Issue by Manu343726** [foonathan/cppast#44]
Hi,

I'm trying to generate reflection information of class constructors, and I would like to extract the exact signature of a given cpp_constructor as an string. For example:

``` cpp
struct Foo
{
     Foo(int i, const std::string& str);
};
```

would return "Foo(int, const std::string&)" for that Foo constructor.

I've found that manipulating the cpp_type hierarchy myself is a bit tedious (handling all the different kinds of types, cross-referencing types thanks to pointers and reference qualifiers, etc), so I was wondering if you already wrote such a functionality. I see that Standardese outputs full signature function names, but I wasn't sure if Standardese just got the displayname from libclang (which is complete iirc) or if it implemented a complex get-function-signature algorithm like what I need.

After checking Standardese sources for 30m I didn't find anything like that, so here I am asking for some pointers in that regard.

Thanks.

**Comment by foonathan** [comment]
There is a `signature()` member function that should do exactly that.

**Comment by Manu343726** [comment]
no... really? Thank you, and sorry for this....
