### ISSUE TITLE
Parsing fails at the end of the file with "no tokens available" message

### ISSUE THREAD

**Issue by rokups** [foonathan/cppast#45]
* cppast version: latest
* clang version: 5.0.1

In addition to issue explained to the title cppast output also does not show base classes. Could it be related?

Input file: https://github.com/rokups/Urho3D/blob/master/Source/Urho3D/IO/AbstractFile.h
Input flags: `-std=c++11`

Output of `cppast -v -I . -I .. -D URHO3D_API --std c++11 IO/AbstractFile.h`:
```
[preprocessor] [debug] IO/AbstractFile.h:25: parsing include '../IO/Serializer.h'
[preprocessor] [debug] IO/AbstractFile.h:26: parsing include '../IO/Deserializer.h'
[libclang parser] [debug] IO/AbstractFile.h:28: parsing cursor of type 'Namespace'
[libclang parser] [debug] IO/AbstractFile.h:32: parsing cursor of type 'ClassDecl'
[libclang parser] [debug] IO/AbstractFile.h:32: parsing cursor of type 'attribute(visibility)'
[libclang parser] [debug] IO/AbstractFile.h:36: parsing cursor of type 'CXXConstructor'
[libclang parser] [debug] IO/AbstractFile.h:38: parsing cursor of type 'CXXConstructor'
[libclang parser] [debug] IO/AbstractFile.h:40: parsing cursor of type 'CXXDestructor'
[libclang parser] [debug] IO/AbstractFile.h:43: parsing cursor of type 'UnexposedDecl'
[libclang parser] [error] IO/AbstractFile.h:43: no tokens available
AST for 'IO/AbstractFile.h':
|-../IO/Serializer.h (include directive): `#include "../IO/Serializer.h"`
|-../IO/Deserializer.h (include directive): `#include "../IO/Deserializer.h"`
+-Urho3D (namespace)
  +-AbstractFile (class) [definition]: `class AbstractFile;`
    |-public (access specifier): `public:`
    |-AbstractFile (constructor) [definition]: `AbstractFile();`
    |-AbstractFile (constructor) [definition]: `explicit AbstractFile(unsigned int size);`
    +-~AbstractFile (destructor) [definition]: `virtual ~AbstractFile()=default;`
```

**Comment by foonathan** [comment]
It's probably the single semicolon at the end of the namespace that's confusing it.

I don't think base classes are shown in the AST there.

**Comment by foonathan** [comment]
Confirmed, it is the unnecessary semicolon, fix will be deployed soon.

**Comment by rokups** [comment]
I tried the fix and unfortunately it crashes at [this line](https://github.com/foonathan/cppast/blob/300854a6b024769ec94a092e2aedfc16d2e8be99/src/libclang/cxtokenizer.cpp#L81).

By the way with and without fix commit semicolon at the end of namespace in the middle of file ([like here](https://github.com/rokups/Urho3D/blob/master/Source/Urho3D/Scene/SceneEvents.h#L105)) causes `warning: unhandled cursor of kind 'UnexposedDecl'`. This might be related.

[SceneEvents.h.cppast.txt](https://github.com/foonathan/cppast/files/1815670/SceneEvents.h.cppast.txt)
[SceneEvents.h.pp.txt](https://github.com/foonathan/cppast/files/1815671/SceneEvents.h.pp.txt)

**Comment by foonathan** [comment]
Sorry, forgot to add a unit test apparently.

Now properly fixed.
