### ISSUE TITLE
error: invalid filename for #line directive on windows

### ISSUE THREAD

**Issue by rokups** [foonathan/cppast#46]
* cppast version: latest
* clang version: 5.0.1 / 6.0.0
* MSVC 19.12.25834.0 (vs 2017)

Input cpp file:
```cpp
#include <type_traits>
void foo() { }
```

Output:
```
cppast.exe --msvc_extensions --msvc_compatibility test.cpp
[preprocessor] [error] In file included from ..\test.cpp: 1:
[preprocessor] [error] C: \Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\type_traits(2518):  error: invalid filename for #line directive
[preprocessor] [error] <scratch space>:70: note: expanded from here
[preprocessor] [error] In file included from ..\test.cpp: 1:
[preprocessor] [error] C: \Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\type_traits(2544):  error: invalid filename for #line directive
[preprocessor] [error] <scratch space>:69: note: expanded from here
[preprocessor] [error] In file included from ..\test.cpp: 1:
[preprocessor] [error] C: \Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\type_traits(2548):  error: invalid filename for #line directive
[preprocessor] [error] <scratch space>:70: note: expanded from here
[preprocessor] [error] In file included from ..\test.cpp: 1:
[preprocessor] [error] C: \Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\type_traits(2552):  error: invalid filename for #line directive
[preprocessor] [error] <scratch space>:69: note: expanded from here
[preprocessor] [error] In file included from ..\test.cpp: 1:
[preprocessor] [error] C: \Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\type_traits(2563):  error: invalid filename for #line directive
[preprocessor] [error] <scratch space>:69: note: expanded from here
[preprocessor] [error] In file included from ..\test.cpp: 1:
[preprocessor] [error] C: \Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\type_traits(2567):  error: invalid filename for #line directive
[preprocessor] [error] <scratch space>:70: note: expanded from here
[preprocessor] [error] In file included from ..\test.cpp: 1:
[preprocessor] [error] C: \Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\type_traits(2571):  error: invalid filename for #line directive
[preprocessor] [error] <scratch space>:69: note: expanded from here
[preprocessor] [error] In file included from ..\test.cpp: 1:
[preprocessor] [error] C: \Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\type_traits(2583):  error: invalid filename for #line directive
[preprocessor] [error] <scratch space>:69: note: expanded from here
[preprocessor] [error] In file included from ..\test.cpp: 1:
[preprocessor] [error] C: \Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\type_traits(2587):  error: invalid filename for #line directive
[preprocessor] [error] <scratch space>:70: note: expanded from here
[preprocessor] [error] In file included from ..\test.cpp: 1:
[preprocessor] [error] C: \Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\type_traits(2591):  error: invalid filename for #line directive
[preprocessor] [error] <scratch space>:69: note: expanded from here
[fatal parsing error] preprocessor: command 'C:/LLVM/bin/clang++.exe -x c++ -E -CC -dD -Xclang -dI -fno-caret-diagnostics -fno-show-column -fdiagnostics-format=msvc -Wno-macro-redefined -Wno-pragma-once-outside-header -Wno-pragma-system-header-outside-header -Wno-include-next-outside-header -IC:/LLVM -D__cppast__="libclang" -D__cppast_version_major__="0" -D__cppast_version_minor__="0" -std=c++14 -fms-compatibility -fms-extensions "test.cpp"' exited with non-zero exit code (1)
``

**Comment by rokups** [comment]
pp file is not produced at all

**Comment by foonathan** [comment]
Right, that error message is generated by the clang++ executable itself, my preprocessor hasn't even executed yet.

If you run `C:/LLVM/bin/clang++.exe -x c++ -E -CC -dD -Xclang -dI -fno-caret-diagnostics -fno-show-column -fdiagnostics-format=msvc -Wno-macro-redefined -Wno-pragma-once-outside-header -Wno-pragma-system-header-outside-header -Wno-include-next-outside-header -IC:/LLVM -D__cppast__="libclang" -D__cppast_version_major__="0" -D__cppast_version_minor__="0" -std=c++14 -fms-compatibility -fms-extensions "test.cpp"`, you should see the same error messages.

**Comment by rokups** [comment]
Yep. Attached to this message files with stdout and stderr outputs of that clang++ command. Hope they will prove useful.
[out.txt](https://github.com/foonathan/cppast/files/1811774/out.txt)
[err.txt](https://github.com/foonathan/cppast/files/1811775/err.txt)

**Comment by foonathan** [comment]
Could you also give me the corresponding lines of `<type_traits>` where the failure occurs?

**Comment by rokups** [comment]
```cpp
#define _DEBUGGER_STEP_OVER 15732479 // 0xf00f00 - 1
#define _DEBUGGER_STEP_INTO 16707565 // 0xfeefee - 1
// <...>
#line _DEBUGGER_STEP_INTO
// <...>
#line _DEBUGGER_STEP_OVER
```

**Comment by foonathan** [comment]
Okay, this seems to be an issue with clang. As a workaround I can simply hide those error messages.

**Comment by foonathan** [comment]
Now the errors will still happen, however they do not cause preprocessing to be aborted.

**Comment by rokups** [comment]
Thank you very much for this fix (and others). I will test this on windows in some time soon.

**Comment by rokups** [comment]
Just tested HEAD revision and still exact same errors persist.

**Comment by foonathan** [comment]
Could you see whether the added `harmless_diag` is ever set to `true`? I can't reproduce the error.

**Comment by rokups** [comment]
Ohh i see what you did here. Errors are still displayed but parsing does not halt. I would suggest silencing these errors though. Console drowns in these errors when parsing something a bit bigger and important messages get lost.

**Comment by foonathan** [comment]
Yeah, that's tricky because I get it line by line, I can easily hide the lines `[preprocessor] [error] C: \Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\type_traits(2571):  error: invalid filename for #line directive`, but then there's just a bunch of `[preprocessor] [error] In file included from ..\test.cpp: 1:` and `[preprocessor] [error] <scratch space>:69: note: expanded from here`...

**Comment by rokups** [comment]
Hmm yes... Hiding that one error does not help my case. There are bunch of `<scratch space>` errors too. Problem is that after huge spam of these errors cppast still terminates and no AST is parsed.
```
<...>
[preprocessor] [error] In file included from Urho3D\Audio/../Core/Object.h: 27:
[preprocessor] [error] <scratch space>:234: note: expanded from here
[preprocessor] [error] In file included from Urho3D\Audio\Audio.h: 29:
[preprocessor] [error] In file included from Urho3D\Audio/../Core/Object.h: 27:
[preprocessor] [error] <scratch space>:234: note: expanded from here
[preprocessor] [critical] too many errors emitted, stopping now [-ferror-limit=]
AST for 'Urho3D\Audio\Audio.h':
```
Could that be worked around somehow?

**Comment by foonathan** [comment]
I can't do anything about the "too many errors emitted" sadly, I just run clang. Is the ` _DEBUGGER_STEP_OVER` macro conditionally guarded somehow? If so, I can maybe remove it with automatic flags.

If not, you should file a bug report for clang.

**Comment by rokups** [comment]
Problematic lines are indeed guarded by `_DEBUG_FUNCTIONAL_MACHINERY` and defining it gets rid of error messages. Although cppast still fails to get ast for Audio.h (only on windows). `-v` parameter produces empty pp file. But that is probably another issue.

**Comment by foonathan** [comment]
Could you check whether the linked commit resolves it?

> Actually i am not quite sure what is going on with Audio.h. cppast.exe fails to parse AST but it appears to work in my own application.

Please investigate and file another issue (maybe you do fast preprocessing in one but not the other?).

**Comment by rokups** [comment]
Ah no need to reopen this one. I forgot to mention that issues with Audio.h were solved by enabling c++14 standard. Possibly windows headers are no longer c++11-compatible? Earlier i had `_DEBUG_FUNCTIONAL_MACHINERY` defined myself so that define + c++14 solves issue. Thank you!

**Comment by foonathan** [comment]
Could you check the commit anyway? It should define the macro automatically, but I'm not sure whether it gets the correct value.

**Comment by rokups** [comment]
Tested and it works good :+1:
