### ISSUE TITLE
Support for custom llvm binary download URL

### ISSUE THREAD

**Issue by Manu343726** [foonathan/cppast#49]
Hi,

To have reliable builds I'm thinking about patching `external/external.cmake` to allow passing a custom LLVM download URL (Say an internal binary server instead of pulling directly from LLVM releases). I would like to know your opinion on this.

Thanks in advance.

**Comment by Manu343726** [comment]
In that case, from what I see from the script, there's no need to propagate the downloaded llvm version to any of the cmake llvm version variables right? (The min version is checked from the llvm-config binary).

**Comment by foonathan** [comment]
Yes.

Under Windows the precompiled binaries don't contain llvm-config, so then you have to set the variables all manually anyway.
