### ISSUE TITLE
Expose __attribute__ and __declspec attributes

### ISSUE THREAD

**Issue by rokups** [foonathan/cppast#50]
I found myself in need of these attributes. When generating bindings it is useful to know if certain type is exported from dll or not. These attributes are used for exactly this purpose and it would be extremely handy to get info. I myself hacked a sort of working solution: https://github.com/rokups/Urho3DNet/commit/50babf20f4003f1c248b029d232f8c3452e47a9b. If you think it is good enough i can submit a PR. If not - this is a feature request then :)

**Comment by foonathan** [comment]
Based on a quick reading of the documentation for `__attribute__` and `__declspec` your code allows more than what is allowed there — but this doesn't matter.

So please submit a PR.
