### ISSUE TITLE
Problems with spaces in paths

### ISSUE THREAD

**Issue by rokups** [foonathan/cppast#56]
This is a very odd issue. I have encountered it on my local windows VM while CI on appveyor does not have this issue. Same code is used in both places.

Using cppast causes application to terminate because clang executable invocation returns non-zero return code. This happens because clang include directory is passed unquoted so `-IC:/Program` is treated as include directory and `Files/LLVM/...` is treated as source file which wont be found and cause clang to fail.

I have made a workaround quoting paths that contain spaces: https://github.com/rokups/Urho3D/commit/7f7423c2e5101dce30f08e662cbd703400b9e09a
For some reason quoting all paths caused parsing errors in my project. Given obscurity of the issue i am not sure if this is a right fix. If its good enough - let me know and i will submit a PR. If not - please look into it whenever possible :)

Edit: just realized I quoted path so wrong. Shame on me.

**Comment by foonathan** [comment]
The fix I did should work.

> Edit: just realized I quoted path so wrong.

What do you mean?

**Comment by rokups** [comment]
My quotes are around the path only, not around entire parameter. No idea why it worked heh. Thank you for the fix 👍
