### ISSUE TITLE
How to selectively parse a header file

### ISSUE THREAD

**Issue by Muzza** [foonathan/cppast#59]
I want to parse a header file and run through the AST. I'm using the Tool code as a base.
My code layout is like this:
```
// MyCppFile.cpp
#include "DataXYZ.h"
#include "MyHeader.h" // makes use of things in DataXYZ.h
```
If I parse just MyHeader.h, it cannot see DataXYZ, (as expected), and so there are unknown types. So I want to parse MyCppFile.cpp, run through the AST and only pay attention to the entries once I hit MyHeader.h

I thought I could achieve this by parsing MyCppFile.cpp, then visiting the AST until I get to the relevant include_directive_t and then parsing everything inside that, but the AST does not seem to include anything outside of the original source file.

I've tried a few other approaches too, with no luck, and I feel like I'm missing something simple.
Can you clarify how I should be approaching this please?

**Comment by foonathan** [comment]
The include directive is not the header file, yes, it is merely the directive.

However, it can give you the file name and you can then parse the included file and check it. This is done automatically by the `resolve_includes()` function: https://github.com/foonathan/cppast/blob/master/include/cppast/parser.hpp#L224
