### ISSUE TITLE
Why can't read multiple attributes?

### ISSUE THREAD

**Issue by fesily** [foonathan/cppast#60]
* cppast version:  last one
* parser: `libclang_parser` 
* clang version:  6.0.0

Explanation of the error.

Input:

```cpp
[[gnu::always_inline]] [[gnu::hot]] [[gnu::const]] [[nodiscard]]
inline int f(); // declare f with four attributes.
//this is ok,but cppast only read last attribute(nodiscard)
//https://en.cppreference.com/w/cpp/language/attributes
```

Input flags: 

Output:

```
Output of `cppast -v <input>`
```

**Comment by foonathan** [comment]
This is probably the same issue as #41, as a workaround you can use `[[gnu::always_inline, gnu::hot, gnu::const, nodiscard]]`.
