### ISSUE TITLE
Integer promotion issue in 32 bit builds

### ISSUE THREAD

**Issue by Manu343726** [foonathan/cppast#66]
- cppast version: See [Manu343726/cppast:master vs foonathan/cppast:master](https://github.com/foonathan/cppast/compare/master...Manu343726:master)
 - LLVM/libclang version: 4.0.0, but I think is not related and would repro with all versions

It seems that `std::size_t` is not `unsigned long long` in 32 bit builds. I would change the hash type to `std::uin64_t` or `unsigned long long`.

``` shell
/home/conan/build/cppast-src/src/../include/cppast/cpp_entity_index.hpp:26:43: error: large integer implicitly truncated to unsigned type [-Werror=overflow]
         constexpr std::size_t fnv_basis = 14695981039346656037ull;       
                                           ^                       
/home/conan/build/cppast-src/src/../include/cppast/cpp_entity_index.hpp:27:43: error: large integer implicitly truncated to unsigned type [-Werror=overflow]
         constexpr std::size_t fnv_prime = 1099511628211ull; 
```

**Comment by foonathan** [comment]
Could you prepare a PR?

**Comment by Manu343726** [comment]
Of course.
