### ISSUE TITLE
Migrate CI to docker-based jobs

### ISSUE THREAD

**Issue by Manu343726** [foonathan/cppast#68]
this helps a lot reducing job execution time (No install/update steps), and also allows you to control your CI sandbox (You can also run that same build locally). Also, CI scripts often end up being simpler (No install/updates, fewer lines).

As a starting point, I always pick [the official Conan images](https://github.com/conan-io/conan-docker-tools), which have images for all major gcc and clang versions. [My own images](https://hub.docker.com/r/manu343726/tinyrefl/tags/) are customized versions of these conan images.

**Comment by foonathan** [comment]
This sounds great. Again, if you could do a PR, I've never used docker.

**Comment by Manu343726** [comment]
I'm currently setting up a CI-only mirror on gitlab of my fork so you can see the differences. I use gitlab-ci bc I can run the ci jobs locally, **in exactly the same way the online service will do**.

*The CI setup I'm doing for you is basically a copy-paste of the tinyrefl setup, so don't worry, it will be maintained.*

> I've never used docker

Don't worry, everything is wrapped into easy-to-use `build.sh` (to build and push the images to dockerhub) and `pull.sh` (to pull latest image versions from dockerhub, in case you have multiple dev machines or something). In case you want to learn and understand docker there are a lot of tutorials out there, but that level of knowledge is not needed for this. Just a few bullets:

 - Docker containers are sandboxed linux machines running in your host linux. It's not a VM but normal linux processes run by the host, isolated by sandboxing features of the kernel. That's why they are that lightweight compared to VMs.

 - Images are "frozen" machines. You start a container by "running" an image. Think of it as a linux that was suspended and you fire it up again.

 - Dockerfile is a "template" for an image, a **recipe of commands you use to build your customized image from other base image**. Like, get conan gcc 5 debian image, install boost on it, and save it.

 - CI services use docker containers as the execution sandbox, using the image you say as an starting point. The usual process for Docker-enabled CI is **pull image, execute image, run user script on container**.

**Comment by Manu343726** [comment]
BTW both `run.sh` and `build.sh` have `REPO` and `NAME` variables which correspond to the docker repository (Your dockerhub account name) and name of the image. You need a valid [dockerhub](https://hub.docker.com/) account and to login first in orther to run `build.sh`:

``` shell
$ sudo docker login
# Your dockerhub user
# Your dockerhub password
```

**Comment by Manu343726** [comment]
Oh, CMake-shit: It seems that invoking `enable_testing()` from there does not work, I've moved the call to the main CMakeLists.txt (just before the `enable_subdirectory(tests)`) and now it magically works....

**Comment by Manu343726** [comment]
CI-only mirror [here](https://gitlab.com/Manu343726/cppast-ci/tree/gitlab-ci). Note it's a separated branch from master.

First CI pipeline running [here](https://gitlab.com/Manu343726/cppast-ci/pipelines/28799138).
*There's a trick with the gitlab-ci: The free available cloud runners somehow have an scheduling policy that's not specially compatible with C++ dev: It seems that many containers/jobs are triggered in the same physical machine, so with X~=20 jobs per build, all doing `make -j4` at the same time, the system gets a bit..... Unstable.*

*From my experience, it takes one or two presses to the "Try again" button to run successfully a build as huge as this. However, note that you can use your own PC (Or mine) as a runner, that may help.*

**Comment by Manu343726** [comment]
I've added a `run_job.sh` script to easily run your CI jobs locally with your current sources.
The difference from running locally with `gitlab-runner` is that `gitlab-runner` required the changes to be committed in order to run the job. Also, `gitlab-runner` does not export the buildtree (The job is completely sandboxed), which could be an issue if you're trying to debug a failing job. Also, it does not require an installed and configured `gitlab-runner`, just docker.

``` shell
$ sudo ./ci/run_job.sh linux-gcc6-x86-llvm400
```
that will build and run the job with the sources in their current state, using a buildtree located at `srcdir/build_jobname_containerhostname`.

There's also a `--clean-build` flag in case you want to run a build from scratch.

**Comment by foonathan** [comment]
Can I just keep using Travis?

**Comment by Manu343726** [comment]
Of course. I will PR you the changes
