### ISSUE TITLE
Basic usage

### ISSUE THREAD

**Issue by burgreen** [foonathan/cppast#71]
* cppast version: latest one 
* parser: `libclang_parser` 
* clang version: 7.0.0

Basic use of tool/main.cpp executable to print the AST of a complex source file: After including the appropriate directories, I get this error:
```
$ ./cppast ~/codes/x/Ox/Mesh/MeshS.h -I ~/codes/x/include -I ~/codes/x -I ~/codes/x/Ox -I ~/dev/llvm/7.0.0/include/
[libclang] [error] /usr/include/sys/resource.h:196: unknown type name 'uint8_t'
[libclang] [error] /usr/include/sys/resource.h:197: unknown type name 'uint64_t'
[libclang] [error] /usr/include/sys/resource.h:198: unknown type name 'uint64_t'
[libclang] [error] /usr/include/sys/resource.h:199: unknown type name 'uint64_t'
[libclang] [error] /usr/include/sys/resource.h:200: unknown type name 'uint64_t'
[libclang] [error] /usr/include/sys/resource.h:201: unknown type name 'uint64_t'
[libclang] [error] /usr/include/sys/resource.h:202: unknown type name 'uint64_t'
[libclang] [error] /usr/include/sys/resource.h:203: unknown type name 'uint64_t'
[libclang] [error] /usr/include/sys/resource.h:204: unknown type name 'uint64_t'
[libclang] [error] /usr/include/sys/resource.h:205: unknown type name 'uint64_t'
[libclang] [error] /usr/include/sys/resource.h:206: unknown type name 'uint64_t'
[libclang] [error] /usr/include/sys/resource.h:210: unknown type name 'uint8_t'
[libclang] [error] /usr/include/sys/resource.h:211: unknown type name 'uint64_t'
[libclang] [error] /usr/include/sys/resource.h:212: unknown type name 'uint64_t'
[libclang] [error] /usr/include/sys/resource.h:213: unknown type name 'uint64_t'
[libclang] [error] /usr/include/sys/resource.h:214: unknown type name 'uint64_t'
[libclang] [error] /usr/include/sys/resource.h:215: unknown type name 'uint64_t'
[libclang] [error] /usr/include/sys/resource.h:216: unknown type name 'uint64_t'
[libclang] [error] /usr/include/sys/resource.h:217: unknown type name 'uint64_t'
Segmentation fault: 11
```

What does this mean? How to resolve? I am obviously a newbie with cppast. 

Could someone provide a "realistic"  example of some typical usage?

**Comment by foonathan** [comment]
This is a typical usage.

Please check what happens for the following file if you don't pass any include directories:

```cpp
#include <cstdint>
```

If that doesn't work, what's the value of the cmake option `LIBCLANG_SYSTEM_INCLUDE_DIR`?
And where is `cstdint` or `stdint.h` actually located?

**Comment by burgreen** [comment]
Thank you! That was the issue. LIBCLANG_SYSTEM_INCLUDE_DIR was pointing to: ~/dev/llvm/7.0.0/include. The correct path was: ~/dev/llvm/7.0.0/include/c++/v1. Recompiled using that update, and the errors are gone. 

Your blog post mentioned that cppast does not parse function bodies. Is that still the case? 

How much effort would be required to parse function bodies? I am looking for ways to extract a full functional dependency tree of complex C++ code.

**Comment by foonathan** [comment]
It's a lot of effort, sadly.

**Comment by burgreen** [comment]
Eh, thought it would be. Any recommendations of tools that provide the desired tree?
