### ISSUE TITLE
Error with comments is macro parameters

### ISSUE THREAD

**Issue by ilyapopov** [foonathan/cppast#73]
* cppast version: 5b3945fa77a2fbfa51f9c68433e112bdde0a5ef1
* parser: `libclang_parser` 
* clang version: 7.0.0

Input:

1.hpp:
```cpp
#define macro(/* comment */ x) ((x)*(x))
```

Input flags: 

    standardese 1.cpp

Output:

```
parsing C++ files...
[preprocessor] [error] xxx/1.hpp:1: invalid token in macro parameter list
parsing documentation comments...
generating documentation...
writing files in format 'html'...
```

PS: this bug appears to be a duplicate of https://github.com/foonathan/cppast/issues/22 .

Unfortunately, the offending code belongs to a third-party library and I cannot change it.

**Comment by foonathan** [comment]
Could you modify the standardese source code here: https://github.com/foonathan/standardese/blob/develop/tool/main.cpp#L432

Add a `compile_config.fast_preprocessing(true)` and see if that is able to parse everything.

**Comment by ilyapopov** [comment]
Yes, it parses everything without errors. Only the output seems empty.
