### ISSUE TITLE
EXC_BAD_ACCESS error

### ISSUE THREAD

**Issue by JohnCoates** [foonathan/cppast#77]
* cppast version: latest
* parser: `libclang_parser`
* clang version: 7.0.1

Explanation of the error.
Trying to parse llvm 7.0.1 llvm/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp

Input:

How do I get it down to a minimal source code?
I've attached the output of
```
/usr/local/bin/clang -x c++ -E -dD -CC -Xclang -dI -fno-caret-diagnostics -fno-show-column -fdiagnostics-format=msvc -Wno-macro-redefined -Wno-pragma-once-outside-header -Wno-pragma-system-header-outside-header -Wno-include-next-outside-header "-I/usr/local/include" "-I/usr/local/lib/clang/7.1.0/include" "-I/System/Library/Frameworks" "-I/Library/Frameworks" "-I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1" "-std=c++14" "-stdlib=libc++" "-I/Users/macbook/Dev/Clones/llvm/build/lib/Target/AArch64/"  \
"-I/Users/macbook/Dev/Clones/llvm/llvm/lib/Target/AArch64" \
/Users/macbook/Dev/Clones/llvm/llvm/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp
```

Input flags: 
```
cppast \
-I /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 \
-I /Users/macbook/Dev/Clones/llvm/build/lib/Target/AArch64/ \
-I /Users/macbook/Dev/Clones/llvm/llvm/lib/Target/AArch64 \
/Users/macbook/Dev/Clones/llvm/llvm/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp
```
Output:

```
Thread 1: EXC_BAD_ACCESS (code=1, address=0x10)
[AArch64AsmParser.cpp.txt.zip](https://github.com/foonathan/cppast/files/2974828/AArch64AsmParser.cpp.txt.zip)

```

P.S. Found another bug while trying to debug this. When launched through lldb it fails to find a valid clang binary. Some sort of error with fork()?

**Comment by foonathan** [comment]
Are you trying to run cppast on clang itself?

I can't really help you sadly as I do not have access to MacOS...

**Comment by JohnCoates** [comment]
Yes I'm trying to run it on clang itself. I'm guessing you'll get a memory error on any platform when trying to run it on that file.

**Comment by foonathan** [comment]
It works for me without problem. But I did not know how to generate the `.inc` files, so I just `touch`ed them, maybe they are the issue?

**Comment by JohnCoates** [comment]
Yeah, I believe the .inc files are the issue. To make those files you have to run `make AArch64CommonTableGen`

**Comment by foonathan** [comment]
So, I finally have gotten some time to take a look at it again.

It seems to be an OOM error, yes. In case you don't need it, a workaround is to not generate the inc files, sorry.
