### ISSUE TITLE
Linker error when build using libclang-8

### ISSUE THREAD

**Issue by satya-das** [foonathan/cppast#78]
* cppast version: latest one
* clang version: 8.0

> /usr/bin/ld: test/CMakeFiles/cppast_test.dir/test.cpp.o: undefined reference to symbol '_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEaSEPKc@@GLIBCXX_3.4.21'
//usr/lib/x86_64-linux-gnu/libstdc++.so.6: error adding symbols: DSO missing from command line
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by foonathan** [comment]
I've just now gotten access to clang 8, but my build works fine. Have you completely rebuild all dependencies?

**Comment by foonathan** [comment]
I've added CI for llvm8, it all works there.

Issue must be on your end, closing for now.
