### ISSUE TITLE
libclang_parser error upon explicit template instantiation

### ISSUE THREAD

**Issue by manuka89** [foonathan/cppast#82]
Hi there,

I have started to use the latest cppast with clang-8 on CentOS.

I'm doing some tests and I wrote the following small code:

template <typename T>
class Test
{
  T m_Member;
};
template class Test<double>;

When I try to run the cppast tool to display the tree I got the following:

./tool/cppast --verbose --file demo.cpp 
[libclang parser] [debug] demo_bug.cpp:2: parsing cursor of type 'ClassTemplate'
[libclang parser] [debug] demo_bug.cpp:4: parsing cursor of type 'FieldDecl'
[libclang parser] [debug] demo_bug.cpp:7: parsing cursor of type 'ClassDecl'
[libclang parser] [error] demo_bug.cpp:7: expected a bracket, got 'class'
AST for 'demo.cpp':
+-Test (class template) [definition]: `template<typename T> class Test;`
  +-m_Member (member variable): `T m_Member;`

I receive an error on the explicit template instantiation: 
[libclang parser] [error] demo_bug.cpp:7: expected a bracket, got 'class'

Although when I run the clang comment directly:
clang++ -std=c++11 -Xclang -ast-dump -fsyntax-only ./demo.cpp

```
`-ClassTemplateSpecializationDecl 0x100102b0 <line:7:1, col:27> col:16 class Test definition
  |-DefinitionData pass_in_registers standard_layout trivially_copyable trivial literal
  | |-DefaultConstructor exists trivial needs_implicit
  | |-CopyConstructor simple trivial has_const_param needs_implicit implicit_has_const_param
  | |-MoveConstructor exists simple trivial needs_implicit
  | |-CopyAssignment trivial has_const_param needs_implicit implicit_has_const_param
  | |-MoveAssignment exists simple trivial needs_implicit
  | `-Destructor simple irrelevant trivial needs_implicit
  |-TemplateArgument type 'double'
  |-CXXRecordDecl 0x10010498 prev 0x100102b0 <line:2:1, col:7> col:7 implicit class Test
  `-FieldDecl 0x10010558 <line:4:3, col:5> col:5 m_Member 'double':'double'
```

**Comment by manuka89** [comment]
For me it looks like that it is inside the function parse_class_kind:
 
 if (detail::skip_if(stream, "template"))
    	// skip template parameters
        detail::skip_brackets(stream);

**Comment by manuka89** [comment]
Sorry, here is the code:

```
template <typename T>
class Test
{
  T m_Member;
};
template class Test<double>;

```

**Comment by manuka89** [comment]
I know it is not so elegant but by adding the following test the problem is solved:

    ```
if (detail::skip_if(stream, "template"))
    {
    	// skip template parameters
    	if (*(stream.cur()) == "<")
    		detail::skip_brackets(stream);
    }
```

**Comment by manuka89** [comment]
There is another issue with this that as it is market as a "template specialization" there is no attribute in it.
I mean when I call cpp_class_template::class_() and I want to visit the fields, the class is empty.

**Comment by manuka89** [comment]
Why do you think it does not visit this child? It is related to libclang?

**Comment by foonathan** [comment]
Can you do a PR with your fix? Most of the parsing code is non-elegant, so don't worry about it; just add a comment. 

The other thing is related to libclang can't do anything about it.

**Comment by manuka89** [comment]
Thank you for your response. I will make a PR to push my fix.
