### ISSUE TITLE
Can not parse headers

### ISSUE THREAD

**Issue by sasq64** [foonathan/cppast#86]
Using the example/tool code as a base, I have tried parsing a simple project, but I only see entities that are defined in the cpp-file, not included headers -- what am I missing?

For instance, if I have a _utils.cpp_ with the single line `#include "utils.h"`, I see nothing, but if I paste the contents of _utils.h_ into _utils.cpp_ it works.
Since the include file lies along side the cpp file it should work even if there is a problem with flags/ include paths?

I get the _include_directive_t_ entity, but that's all.

**Comment by foonathan** [comment]
You have to explicitly pass the header to the tool to get the header.
