### ISSUE TITLE
python binding

### ISSUE THREAD

**Issue by djn3m0** [foonathan/cppast#88]
Hi,

Is there any python binding for this? Or Is there an easy way of just dump the full AST(Ideally in JSON) in python and do the rest of the parsing there?

Thank you

**Comment by bjodah** [comment]
Potentially pybind11 bindings could be generated from the AST itself (essentially bootstrapping the wrapper if cppast is used for it). I've seen attempts to automate the binder generation (using libclang):
- https://github.com/RosettaCommons/binder
- https://github.com/ranr01/pybind11-code-generator

(binder might be more than an attempt, but I find the documentation lacking).

**Comment by foonathan** [comment]
> Is there any python binding for this?

There are python bindings for libclang itself, they might work for you: https://eli.thegreenplace.net/2011/07/03/parsing-c-in-python-with-clang

> Or Is there an easy way of just dump the full AST(Ideally in JSON) in python and do the rest of the parsing there?

See https://github.com/foonathan/cppast/blob/master/tool/main.cpp#L127. you should be able to modify it into any format you want.
