### ISSUE TITLE
CMake error when clang is built from github

### ISSUE THREAD

**Issue by Nisiyama-Suzune** [foonathan/cppast#92]
* cppast version: latest one
* parser: `libclang_parser` 
* clang version: 10.0.0

When clang is builded from `github.com/llvm/llvm-project.git`, `llvm-config --includedir` is misdirected since `--includedir` gives only llvm headers but not libclang headers.

Input:

```
mkdir build
cd build
cmake ..
```

**Comment by Nisiyama-Suzune** [comment]
`cmake -G"Unix Makefiles" -DLLVM_VERSION_EXPLICIT=10.0.0 -DLIBCLANG_LIBRARY="<dir>/llvm-project/build/lib/libclang.so" -DLIBCLANG_INCLUDE_DIR="<dir>/llvm-project/clang/include" -DCLANG_BINARY="<dir>/llvm-project/build/bin/clang++" ../` seems to be a workaround. Substitute `<dir>` with the cloned directory.

**Comment by foonathan** [comment]
Yes, that seems to be what you need to do. I don't really see what I can do generally to detect that.
