### ISSUE TITLE
Not initialized process exit code in tiny-process-library leads to fail to find clang on os x mojave

### ISSUE THREAD

**Issue by xorza** [foonathan/cppast#93]
* cppast version: https://github.com/foonathan/cppast/commit/a89ebcdf0a9cb4040fd39b7a4892cc1a0cb4ecbb (latest)
* parser: `libclang_parser`
* clang version: Apple clang 10.0.1

Explanation of the error:
Input:
Any input

Output:
throw std::invalid_argument("unable to find clang binary '" + binary + "'");

On OS X Mojave, Xcode 10.3 we fail to find clang executable even though it is specified `set(CLANG_BINARY clang++)` in CMakeLists and actually found and gives valid output. 

I found problem in **tiny-process-library** here https://github.com/eidheim/tiny-process-library/blob/5bc47531a97f80ac07092ac3ed56a26139c748b3/process_unix.cpp#L129 . 
```
int exit_status;
waitpid(data.id, &exit_status, 0);
```
In my case problem is that exit status isn't initialized with 0 and results in random numbers after waitpid. Problem is completely solved by initializing it with 0.

I tried to open PR against **tiny-process-library**, but owner archived it and it is readonly.
My suggestion is to either fork tiny-process-library repo into your account or just copy its sources to cppast and remove submodule. And then fix `int exit_status **= 0**;`

If you decide to copy tiny-process-library sources, I can do that and open PR.

Thanks

**Comment by foonathan** [comment]
Sorry for the late reply.

You can file a PR (or merge request as its called), at the gitlab repository: https://gitlab.com/eidheim/tiny-process-library

Let me know when you did so, and I'll merge it back.
