### ISSUE TITLE
libclang_parser parsing string argument for custom attributes as floating point literal

### ISSUE THREAD

**Issue by NotAPenguin0** [foonathan/cppast#95]
* cppast version: latest at time of writing
* parser: `libclang_parser`
* clang version: 9.0.0

I am trying to parse the following file

```cpp
#ifndef SATURN_BOX_COLLIDER_COMPONENT_HPP_
#define SATURN_BOX_COLLIDER_COMPONENT_HPP_

#include "ComponentBase.hpp"

#include <glm/glm.hpp>

namespace Saturn::Components {
// clang-format off
struct [[saturn::component, saturn::default_serialize]] BoxCollider
    : ComponentBase {
    // The center of the collider. In object space
    [[saturn::tooltip("The center of the collider.")]] 
	glm::vec3 center;

    [[saturn::tooltip("Half the width of the box for each axis.")]] 
	glm::vec3 half_widths;
};
// clang-format on

} // namespace Saturn::Components

#endif
```

With input flags `-std=c++1z`.

I'm interested in the attributes of the fields here, but when I get to those and try to parse the arguments, it turns out that the parser has parsed the string argument as a `float_literal`, while it should be a `string_literal`. The `spelling` variable is correct though.

**Comment by foonathan** [comment]
Sorry for the delay, issue is now fixed.

Note that the problem wasn't with string literals in attributes, it was string literals with `.` in them... :D

**Comment by NotAPenguin0** [comment]
Ah, great. No worries about the delay, I was able to use a workaround :)
