### ISSUE TITLE
can`t parse inherit ？

### ISSUE THREAD

**Issue by yuinm** [foonathan/cppast#97]
* cppast version: lasest one 
* parser: `libclang_parser` 
* clang version: 7.0

Explanation of the error.
i`m newer about cppast ,  i use the tools 'tool/cppast'  pase my c++ file .

Input:
the input file like this 
![image](https://user-images.githubusercontent.com/13299372/67928643-7b429b00-fbf6-11e9-8788-d85089b5d16d.png)
```cpp
Minimal source code reproducing the error
```

Input flags: 

Output:
the output file  like this , but it`s not show the 'class Object'  inherit from 'class A' . Can I get the relation use cppast。
![image](https://user-images.githubusercontent.com/13299372/67928895-10459400-fbf7-11e9-88a4-3843010d4b26.png)

```
Output of `cppast -v <input>`
```

**Comment by yuinm** [comment]
I found a function bases()  knows the class`s base , but how about  template class`s base

**Comment by foonathan** [comment]
You use https://github.com/foonathan/cppast/blob/master/include/cppast/cpp_class_template.hpp#L27 to get the class, then bases().
